spring.application.name=transformer-ns

# Batch
batch.input-file=file:input.txt
batch.output-file=file:output.txt

# Spring Batch - ne pas lancer le job automatiquement
spring.batch.job.enabled=false

# Base H2 en memoire pour les metadonnees Spring Batch
spring.datasource.url=jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
